version: '3.9'

services:
  api:
    build: .
    container_name: sky-feeder-api
    volumes:
      - .:/app
    env_file:
      - .env
    environment:
      - ENABLE_DATA_STREAM=false
    ports:
      - "${PORT}:${PORT}"
    command: ["api"]

  data-stream:
    build: .
    container_name: sky-feeder-data-stream
    volumes:
      - .:/app
    env_file:
      - .env
    environment:
      - ENABLE_DATA_STREAM=true
    command: ["data-stream"]
