"""more fleshing out on user algorithm records

Revision ID: 47385d516399
Revises: 4e436406f1c5
Create Date: 2024-11-09 15:50:37.949499

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '47385d516399'
down_revision: Union[str, None] = '4e436406f1c5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user_algorithms', sa.Column('algo_manifest', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    op.add_column('user_algorithms', sa.Column('record_name', sa.String(), nullable=True))
    op.add_column('user_algorithms', sa.Column('display_name', sa.String(), nullable=True))
    op.add_column('user_algorithms', sa.Column('description', sa.String(), nullable=True))
    op.drop_column('user_algorithms', 'manifest')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user_algorithms', sa.Column('manifest', sa.TEXT(), autoincrement=False, nullable=True))
    op.drop_column('user_algorithms', 'description')
    op.drop_column('user_algorithms', 'display_name')
    op.drop_column('user_algorithms', 'record_name')
    op.drop_column('user_algorithms', 'algo_manifest')
    # ### end Alembic commands ###
