"""base layer models

Revision ID: 4e436406f1c5
Revises: 
Create Date: 2024-11-09 13:43:54.668633

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '4e436406f1c5'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('posts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('uri', sa.String(), nullable=True),
    sa.Column('cid', sa.String(), nullable=True),
    sa.Column('reply_parent', sa.String(), nullable=True),
    sa.Column('reply_root', sa.String(), nullable=True),
    sa.Column('indexed_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_posts_id'), 'posts', ['id'], unique=False)
    op.create_index(op.f('ix_posts_uri'), 'posts', ['uri'], unique=False)
    op.create_table('subscription_states',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('service', sa.String(), nullable=True),
    sa.Column('cursor', sa.BigInteger(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('service')
    )
    op.create_table('user_algorithms',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.String(), nullable=True),
    sa.Column('algo_uri', sa.String(), nullable=True),
    sa.Column('manifest', postgresql.JSONB(), nullable=True),
    sa.Column('version_hash', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'algo_uri', name='uix_user_algo_uri')
    )
    op.create_index(op.f('ix_user_algorithms_user_id'), 'user_algorithms', ['user_id'], unique=False)
    op.create_table('post_user_algorithm',
    sa.Column('post_id', sa.Integer(), nullable=False),
    sa.Column('user_algorithm_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['post_id'], ['posts.id'], ),
    sa.ForeignKeyConstraint(['user_algorithm_id'], ['user_algorithms.id'], ),
    sa.PrimaryKeyConstraint('post_id', 'user_algorithm_id'),
    sa.UniqueConstraint('post_id', 'user_algorithm_id', name='uix_post_user_algorithm')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('post_user_algorithm')
    op.drop_index(op.f('ix_user_algorithms_user_id'), table_name='user_algorithms')
    op.drop_table('user_algorithms')
    op.drop_table('subscription_states')
    op.drop_index(op.f('ix_posts_uri'), table_name='posts')
    op.drop_index(op.f('ix_posts_id'), table_name='posts')
    op.drop_table('posts')
    # ### end Alembic commands ###
