"""add original feed_did to record

Revision ID: 6806029677d3
Revises: 47385d516399
Create Date: 2024-11-09 16:02:10.812388

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6806029677d3'
down_revision: Union[str, None] = '47385d516399'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user_algorithms', sa.Column('feed_did', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user_algorithms', 'feed_did')
    # ### end Alembic commands ###
