"""Add timestamps

Revision ID: ba3f76ccceaf
Revises: 3c5f3f8acbbf
Create Date: 2024-11-10 15:59:18.239595

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ba3f76ccceaf'
down_revision: Union[str, None] = '3c5f3f8acbbf'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('search_facets', sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False))
    op.add_column('search_facets', sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('search_facets', 'updated_at')
    op.drop_column('search_facets', 'created_at')
    # ### end Alembic commands ###
